# Features, Labels, Dataset Structure, X and y

In [1]:
!pip install numpy pandas matplotlib seaborn

Requirement already satisfied: numpy in .\venv15\Lib\site-packages (2.4.6)
Requirement already satisfied: pandas in .\venv15\Lib\site-packages (3.0.3)
Requirement already satisfied: matplotlib in .\venv15\Lib\site-packages (3.10.9)
Requirement already satisfied: seaborn in .\venv15\Lib\site-packages (0.13.2)
Requirement already satisfied: python-dateutil>=2.8.2 in .\venv15\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\venv15\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: contourpy>=1.0.1 in .\venv15\Lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in .\venv15\Lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in .\venv15\Lib\site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in .\venv15\Lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in .\venv15\Lib\site-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=8 in .\venv15\Lib\site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in .\venv15\Lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in .\venv15\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## Dataset

In [3]:
data={
     "Student_id":[1,2,3,4],
     "Study_hours":[8,2,6,3],
     "Attendance":[90,45,80,50],
     "Previous_marks":[85,40,72,45],
     "Final_result":['Pass','Fail','Pass','Fail']
}
df=pd.DataFrame(data)
df

   Student_id  Study_hours  Attendance  Previous_marks Final_result
0           1            8          90              85         Pass
1           2            2          45              40         Fail
2           3            6          80              72         Pass
3           4            3          50              45         Fail

## Features

In [5]:
x=df[["Study_hours","Attendance","Previous_marks"]]
x

   Study_hours  Attendance  Previous_marks
0            8          90              85
1            2          45              40
2            6          80              72
3            3          50              45

## Labels

In [6]:
y=df["Final_result"]
y

0    Pass
1    Fail
2    Pass
3    Fail
Name: Final_result, dtype: str